AbonnementManager/Controllers/AbonnnementController.cs
using AbonnementManager.Models;
using AbonnementManager.Repository.IRepository;
using ApplicationManager.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace AbonnementManager.Controllers
{
    [Authorize]
    public class AbonnementController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public AbonnementController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Abonnement> objAppList = _unitOfWork.Abonnement.GetAll(includeProperties: "Client,Application").ToList();
            return View(objAppList);
        }
		[HttpGet]
		public IActionResult Upsert(int? id)
        {
            AbonVM abonVM = new()
            {
                ClientList = _unitOfWork.Client.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id_Client.ToString()
                }),
                ApplicationList = _unitOfWork.Application.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id_App.ToString()
                }),
                Abonnement = new Abonnement()
            };
            if (id == null || id == 0)
            {
                //create
                return View(abonVM);
            }
            else
            {
                //update
                abonVM.Abonnement = _unitOfWork.Abonnement.Get(u => u.Id_Abon == id);
                return View(abonVM);
            }
            
        }
        [HttpPost]
        public IActionResult Upsert(AbonVM abonVM)
        {
            if (ModelState.IsValid)
            {
                
                var currentDate = DateOnly.FromDateTime(DateTime.Today);
                var existingAbonnement = _unitOfWork.Abonnement.GetAll()
                    .Where(a => a.IdClient == abonVM.Abonnement.IdClient &&
                               a.IdApp == abonVM.Abonnement.IdApp &&
                               a.DateFin >= currentDate)
                    .FirstOrDefault();
                if (existingAbonnement != null)
                {
                    ModelState.AddModelError("", "Abonnement already exists");
                    abonVM.ClientList = _unitOfWork.Client.GetAll().Select(u => new SelectListItem
                    {
                        Text = u.Name,
                        Value = u.Id_Client.ToString()
                    });
                    abonVM.ApplicationList = _unitOfWork.Application.GetAll().Select(u => new SelectListItem
                    {
                        Text = u.Name,
                        Value = u.Id_App.ToString()
                    });
                    return View(abonVM);
                }

                if (abonVM.Abonnement.Id_Abon == 0)
                {
                    _unitOfWork.Abonnement.Add(abonVM.Abonnement);
                }
                else
                {
                    _unitOfWork.Abonnement.Update(abonVM.Abonnement);
                }

                _unitOfWork.Save();
                //TempData["success"] = "Product created successfully";
                return RedirectToAction("Index");
            }
            else
            {
                abonVM.ClientList = _unitOfWork.Client.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id_Client.ToString()
                });
                abonVM.ApplicationList = _unitOfWork.Application.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id_App.ToString()
                });

                return View(abonVM);
            }
        }
        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<Abonnement> objProductList = _unitOfWork.Abonnement.GetAll(includeProperties: "Client,Application").ToList();
            return Json(new { data = objProductList });
        }


        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var productToBeDeleted = _unitOfWork.Abonnement.Get(u => u.Id_Abon == id);
            if (productToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            

            _unitOfWork.Abonnement.Remove(productToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Delete Successful" });
        }

        #endregion
    
    }
}

AbonnementManager/Controllers/ApplicationController.cs
using AbonnementManager.Models;
using AbonnementManager.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AbonnementManager.Controllers
{
    [Authorize]

    public class ApplicationController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ApplicationController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Application> objAppList = _unitOfWork.Application.GetAll().ToList();
            return View(objAppList);
        }
       
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Application obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Application.Add(obj);
                _unitOfWork.Save();
                //TempData["success"] = "Application created successfully";
                return RedirectToAction("Index");
            }
            return View();

        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Application? applicationFromDb = _unitOfWork.Application.Get(u => u.Id_App == id);
            //Application? applicationFromDb1 = _db.Categories.FirstOrDefault(u=>u.Id==id);
            //Application? applicationFromDb2 = _db.Categories.Where(u=>u.Id==id).FirstOrDefault();

            if (applicationFromDb == null)
            {
                return NotFound();
            }
            return View(applicationFromDb);
        }
        [HttpPost]
        public IActionResult Edit(Application obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Application.Update(obj);
                _unitOfWork.Save();
                //TempData["success"] = "Application updated successfully";
                return RedirectToAction("Index");
            }
            return View();

        }
        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<Application> objApplicationList = _unitOfWork.Application.GetAll().ToList();
            return Json(new { data = objApplicationList });
        }


        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var applicationToBeDeleted = _unitOfWork.Application.Get(u => u.Id_App == id);
            if (applicationToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }



            _unitOfWork.Application.Remove(applicationToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Delete Successful" });
        }

        #endregion

    }

}

AbonnementManager/Controllers/ClientController.cs
using AbonnementManager.Models;
using AbonnementManager.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AbonnementManager.Controllers
{
    [Authorize]
    public class ClientController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ClientController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Client> objClientList = _unitOfWork.Client.GetAll().ToList();
            return View(objClientList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Client obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Client.Add(obj);
                _unitOfWork.Save();
                //TempData["success"] = "Client created successfully";
                return RedirectToAction("Index");
            }
            return View();

        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Client? clientFromDb = _unitOfWork.Client.Get(u => u.Id_Client == id);
            //Client? clientFromDb1 = _db.Categories.FirstOrDefault(u=>u.Id==id);
            //Client? clientFromDb2 = _db.Categories.Where(u=>u.Id==id).FirstOrDefault();

            if (clientFromDb == null)
            {
                return NotFound();
            }
            return View(clientFromDb);
        }
        [HttpPost]
        public IActionResult Edit(Client obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Client.Update(obj);
                _unitOfWork.Save();
                //TempData["success"] = "Client updated successfully";
                return RedirectToAction("Index");
            }
            return View();

        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<Client> objClientList = _unitOfWork.Client.GetAll().ToList();
            return Json(new { data = objClientList });
        }


        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var clientToBeDeleted = _unitOfWork.Client.Get(u => u.Id_Client == id);
            if (clientToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }



            _unitOfWork.Client.Remove(clientToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Delete Successful" });
        }

        #endregion
    }
}

AbonnementManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AbonnementManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.2/css/dataTables.dataTables.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    <link rel="stylesheet" href="~/AbonnementManager.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container-fluid">
        <div class="row flex-nowrap">
            @if (User.Identity.IsAuthenticated)
            {
                
            
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <span class="fs-5 d-none d-sm-inline">Abonnement Manager</span>
                    </a>
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="Index" class="nav-link align-middle px-0 text-white">
                                <i class="bi bi-house"></i><span class="ms-1 d-none d-sm-inline">Home</span>
                            </a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            
                        
                        <li class="nav-item">
                            <a asp-area=""  asp-controller="Client" asp-action="Index" class="nav-link align-middle px-0 text-white">
                                <i class="bi bi-person"></i><span class="ms-1 d-none d-sm-inline">Client</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Application" asp-action="Index" class="nav-link align-middle px-0 text-white">
                                <i class="bi bi-file-earmark-check"></i><span class="ms-1 d-none d-sm-inline">Application</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Abonnement" asp-action="Index" class="nav-link align-middle px-0 text-white">
                                <i class="bi bi-file-earmark-person"></i><span class="ms-1 d-none d-sm-inline">Abonnement</span>
                            </a>
							</li>
						}
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Home" asp-action="Privacy" class="nav-link align-middle px-0 text-white">
                                <i class="bi bi-shield-check"></i><span class="ms-1 d-none d-sm-inline">Privacy</span>
                            </a>
                        </li>
                        
                    </ul>
                    <partial name="_LoginPartial" />
                    <hr>

                </div>
            </div>

            }
            <div class="col py-3">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer class=" footer bg-dark text-muted">
        <div class="container text-center ">
            &copy; 2024 - AbonnementManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.tiny.cloud/1/kyot29d4pp7kseq1ps9j9zeumn4vvoredpoq5q4kxsr9501i/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdn.datatables.net/2.1.2/js/dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>